config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :reviews, except: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :author, presence: true
  validates :title, presence: true
  validates :content, presence: true
  accepts_nested_attributes_for :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :article
  validates :name, presence: true
  validates :star, presence: true, inclusion: { in: (0...5) }
  validates :review_content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_path(@article), message: "Aubriagdow!"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    @article.update(article_params)
    if @article.save
      redirect_to article_path(@article), message: "Aubriagdow!"
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path, message: "Artigo #{@article.title} foi excluído!"
  end

private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
      params.require(:article).permit(
        :author,
        :email,
        :title,
        :content,
        :dog_key,
        :cat_key,
        :product_key,
        :pet_key,
        :photo
         )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_article_to_review, only: [:edit, :index, :create]

  def index
    @reviews = @article.reviews
  end

  def new
    @review = Review.new
    set_article_to_review
  end

  def create
    @review = Review.new(review_params)
    @review.article = @article
    # @review = @article.reviews
    if @review.save
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    @review.update(review_params)
    set_article_to_review
    if @review.save
      redirect_to article_path(@article)
    else
     render 'edit'
    end
  end

  def destroy
    set_article_to_review
    @review.destroy
    redirect_to article_path(@article)
  end


private

  def set_review
    @review = Review.find(params[:id])
  end

  def set_article_to_review
    @article = Article.find(params[:article_id])
  end

  def review_params
    params.require(:review).permit(:name, :email, :review_content, :star)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/articles/_form.html.erb
        <%= simple_form_for [@article] do |f| %>
        <%= f.input :author, label: 'Nome do autor', error: 'Nome obrigatório. Por favor, digite um nome'%>
        <%= f.input :email, error: "Favor escreva um email válido" %>
        <%= f.input :title, label: 'Título do artigo', error: 'Título do artigo obrigatório. Por favor, digite um título' %>
        <%= f.input :content,  label: 'Conteúdo do artigo', error: 'Conteúdo obrigatório. Por favor, escreva um conteúdo.', placeholder: 'Nesse espaço, escreva seu artigo...' %>
        <h5> Abaixo, selecione sobre que assunto é seu artigo:</h5>
        <%= f.input :dog_key, label: ". cachorros" %>
        <%= f.input :cat_key, label: '. gatos' %>
        <%= f.input :product_key, label: '. produtos para pets' %>
        <%= f.input :pet_key, label: '. pets em geral' %>
        <%= f.input :photo, label: "Foto do artigo" %>
        <%= f.submit "Cadastrar artigo", class: "btn btn-primary" %>
        <% end %>

app/views/articles/edit.html.erb
<p> Edite esse artigo </p>

<%= render "form" %>

app/views/articles/index.html.erb
<p>
    <%= button_to "Escrever Artigo", new_article_path, method: :get, class: "btn btn-primary btn-lg" %>
</p>
</div>
<div class="container flex">
    <div class="col-xs-12">
        <div class="row">
            <% @articles.each do |article| %>
            <div class="card">
                <%= article.photo %>
                <div class="card-header">
                    <h4 class="link">Título: <b><%= link_to article.title.upcase, article_path(article) %></b></h4>
                </div>
                <div class="card-body">
                    <h5>Autor: <b><%= article.author.capitalize %></b></h5>
                    <p>Email :
                        <%= article.email %>
                    </p>
                </div>
                <div class="div card-footer">
                    <% if article.dog_key %><i class="fas fa-dog"></i>
                    <% else %> <span></span>
                    <% end %>
                    <% if article.cat_key %><i class="fas fa-cat"></i>
                    <% else %> <span></span>
                    <% end %>
                    <% if article.product_key %><i class="fas fa-box-open"></i>
                    <% else %> <span></span>
                    <% end %>
                    <% if article.pet_key %><i class="fas fa-paw"></i>
                    <% else %> <span></span>
                    <% end %>
                </div>
            </div>
            <div class="container" class="trashfa">
                <%= link_to '<i class="fas fa-trash-alt", style="color: pink;"></i>'.html_safe, article_path(article), method: :delete %>
            </div>
            <% end %>
        </div>
    </div>

app/views/articles/new.html.erb
<p> Escreva seu artigo abaixo </p>
<div><%= render "form" %></div>

app/views/articles/show.html.erb
<div class="container title">
    <%= @article.title.titleize %>
</div>
<div class="container author">
    <%= @article.author.capitalize %>
</div>
<div style="height: 25px"></div>
<div class="container keys">
    <p> Este artigo refere-se a...</p>
    <span>
    <% if @article.dog_key %>
    <i class="fas fa-dog"></i>
    <% else %> <span></span>
    <% end %>
    <% if @article.cat_key %><i class="fas fa-cat"></i>
    <% else %> <span></span>
    <% end %>
    <% if @article.product_key %><i class="fas fa-box-open"></i>
    <% else %> <span></span>
    <% end %>
    <% if @article.pet_key %><i class="fas fa-paw"></i>
    <% else %> <span></span>
    <% end %>
    </span>
</div>
<div style="height: 25px"></div>
<div class="container content">
    <%= @article.content %>
</div>
<div class="review">
    <h2> Reviews </h2>
    <%= button_to "Escrever Review", new_article_review_path(@article), method: :get, class:"btn btn-primary btn-lg"%>
    <% @article.reviews.each do |review| %>
    <div>
        <p>Review feita por <b> <%= review.name.capitalize %> </b></p>
    </div>
    <div>
        <span>Como <b><%= review.name.capitalize %></b> avalia o artigo <b><%= @article.title.upcase %></b> de <b><%= @article.author.capitalize %>: </b> </span></div>
    <div class="starsfa"></span>
        <span><% review.star.times do %>
            <i class='fas fa-star'></i>
            <% end %></span></div>
<div>
    <p>
        <%= review.review_content %>
    </p>
</div>
<div>
    <%= button_to "Apagar Review", article_review_path(review.article, review), method: :delete, class: "btn btn-primary btn-sm" %>
</div>
<% end %>
</div>
<p>
    <%= button_to "Apagar Artigo", article_path(@article), method: :delete, class: "btn btn-primary btn-lg" %>
</p>
<div style="height: 25px"></div>
<%= button_to "Editar Artigo", edit_article_path(@article), method: :get, class: "btn btn-primary btn-lg"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>WePetz</title>
    <%= favicon_link_tag "logoprovisorio.jpg" %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway|Spicy+Rice" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'shared/navbar' %>
    <div class="wrapper">
        <div class="container">
          <!--   <h1> Wepetz Blog <span style="margin: 15px;"><i class="fas fa-paw"></i></span></h1> -->
            <%= yield %>
        </div>
    </div>
    <%= render 'shared/footer' %>
</body>

</html>

app/views/reviews/_form.html.erb
<%= simple_form_for [@article, @review] do |f| %>
<%= f.input :name, label: 'Nome', error: 'Nome obrigatório. Por favor, digite um nome'%>
<%= f.input :email %>
<%= f.input :star, label: 'Classifique o Artigo' %>
<%= f.input :review_content,  label: 'Escreva sobre a review', error: 'Conteúdo obrigatório. Por favor, escreva um conteúdo.', placeholder: 'Por favor, deixe seu relato sobre o artigo' %>
<%= f.submit "Submeter Review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/edit.html.erb
<p> Escreva sua review abaixo: </p>
<div>
<%= simple_form_for [@article, @review] do |f| %>
<%= f.input :name, label: 'Nome', error: 'Nome obrigatório. Por favor, digite um nome'%>
<%= f.input :email %>
<%= f.input :star, label: 'Classifique o Artigo', default: 0 %>
<%= f.input :review_content,  label: 'Escreva sobre a review', error: 'Conteúdo obrigatório. Por favor, escreva um conteúdo.', placeholder: 'Por favor, deixe seu relato sobre o artigo' %>
<%= f.submit "Submeter Review", class: "btn btn-primary" %>
<% end %>
</div>

app/views/reviews/new.html.erb
<p> Edit sua review abaixo: </p>
<div>
<%= render "form" %>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="navbar navbar-fixed-bottom" style="max-height: 20px !important">
    <div class="footer-links">
      <a href="https://www.instagram.com/we_petz/" target="_blank"><i class="fab fa-instagram"></i></a>
      <a href="https://www.facebook.com/wepetz/" target="_blank"><i class="fab fa-facebook"></i></a>
    </div>
    <div class="footer-copyright">
      <p> Nós <i class="fa fa-heart"></i> Pets </p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar">
    <!-- Logo -->
    <div id="linkgeral">
    <%= link_to '<i class="fas fa-paw", style="font-size: 50px"> </i>'.html_safe, articles_path %> </div>
    <h1> Wepetz Blog </h1>


    <!-- Right Navigation -->
    <div class="navbar-right hidden-xs hidden-sm">
        <a href="" class="navbar-item navbar-link">Veterinários</a>
        <a href="" class="navbar-item navbar-link">Dicas</a>
        <a href="" class="navbar-item navbar-link">Artigos</a>
        <a href="" class="navbar-item navbar-link">Animais</a>
        <a href="" class="navbar-item navbar-link">Produtos</a>
        <div class="empty-form">
            <form action="#">
                <input type="text" placeholder="Tudo sobre pets" style="max-width: 300px; max-height: 30px;">
                <input type="submit", class= "btn-submit btn-xs", style="background-color: rgba(255,255,102, 0.8); margin: rgba(255,255,102, 0.8)" value="Procurar">
            </form>
        </div>
        <!-- Profile picture with dropdown list -->
        <div class="navbar-item">
            <div class="dropdown">
                <img src="https://kitt.lewagon.com/placeholder/users/pedrofcezar" class="avatar dropdown-toggle" id="navbar-menu" data-toggle="dropdown">
                <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
                    <li><a href="#">Profile</a></li>
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="#">Log Out</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="navbar-item hidden-md hidden-lg">
        <div class="dropdown">
            <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
            <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
                <li><a href="#">Veterinarios</a></li>
                <li><a href="#">Dicas</a></li>
                <li><a href="#">Artigos</a></li>
                <li><a href="#">Animais</a></li>
                <li><a href="#">Produtos</a></li>
            </ul>
        </div>
    </div>
</div>